server:
  port: 8070
spring:
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: 127.0.0.1:8848
        group: test
    gateway:
      discovery:
        locator:
          enabled: true

  application:
    name: node-service
# sidecar 相关的配置
sidecar:
  # 异构微服务的IP
  ip: 127.0.0.1
  # 异构微服务的端口
  port: 8060

  # 异构微服务的健康检查URL(这里不配置的话，默认会认为是UP)
  health-check-url: http://localhost:8060/health.json
# springboot actuator监控相关
management:
  endpoint:
    health:
      show-details: always