
version: '3.8'
services:
  namesrv:
    image: apache/rocketmq:5.3.2
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    networks:
      - rocketmq
    command: sh mqnamesrv
  broker:
    image: apache/rocketmq:5.3.2
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    environment:
      - NAMESRV_ADDR=rmqnamesrv:9876
    depends_on:
      - namesrv
    networks:
      - rocketmq
    volumes:
      - ./conf/broker.conf:/home/rocketmq/rocketmq-5.3.2/conf/broker.conf
    command: sh mqbroker -n rmqnamesrv:9876 --enable-proxy autoCreateTopicEnable=true -c /home/rocketmq/rocketmq-5.3.2/conf/broker.conf
  dashboard:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: dashboard
    networks:
      - rocketmq
    ports:
      - 8082:8082
    depends_on:
      - namesrv
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=rmqnamesrv:9876
networks:
  rocketmq:
    driver: bridge