server:
  port: 18084

spring:
  application:
    name: nacos-config-example
  cloud:
    nacos:
      config:
        serverAddr: 127.0.0.1:8848
        username: 'nacos'
        password: 'nacos'
  config:
    import:
      # 需要先在nacos上创建一个名为nacos-config-example的配置文件
      - nacos:nacos-config-example?refreshEnabled=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug